  
version: "3.9"  # optional since v1.27.0
services:
  # app:
  #   build: .
  #   ports:
  #     - "5050:8080"
  #   environment:
  #     BIND: 0.0.0.0:8080
  #   networks: 
  #     - network_devices            
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    # volumes:
    #   - postgresvolume01:/var/lib/postgresql/data
    networks: 
      - network_devices       
    environment:
      POSTGRES_PASSWORD: net
      POSTGRES_USER: net
      POSTGRES_DB: net
  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    networks: 
      - network_devices        
  redis:
    image: redis:6.2.2
    ports:
      - "6379:6379"
    # volumes:
    #   - redisvolume01:/data
    networks: 
      - network_devices      
# volumes:
#   redisvolume01: {}
#   postgresvolume01: {}
networks:
  network_devices: {}